/*
 * unistd.h
 *
 *  Created on: Nov 15, 2022
 *      Author: a5111060
 */

#ifndef COMMON_FREERTOS_COMMON_COMPILER_SUPPORT_CCRX_UNISTD_H_
#define COMMON_FREERTOS_COMMON_COMPILER_SUPPORT_CCRX_UNISTD_H_



#endif /* COMMON_FREERTOS_COMMON_COMPILER_SUPPORT_CCRX_UNISTD_H_ */
