dtp.enabled=true
dtp.url=http://rel-0055220.adwin.renesas.com:80
dtp.user=CLI_OS_TEAM
dtp.password=jmCPDNYejpY7ieHS1JBaAJSsQZtC/YDdMhZO7hP4f3w=
report.dtp.publish=true
dtp.project=RX-IoT-Ref-LTS3-DA16600
build.id=${env_var:CI_PIPELINE_ID}-${env_var:CI_COMMIT_BRANCH_BUILD_ID}-${time:yyyy-MM-dd}
session.tag=${env_var:CI_COMMIT_BRANCH}
